version: "2"

services:
    web:
        image: nginx:latest
        container_name: api_web
        restart: always
        network_mode: "bridge"
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            #- ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/drupal.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/amplify.conf:/etc/nginx/conf.d/amplify.conf
        links:
            - php
        environment:
          - VIRTUAL_HOST=api.staging.yongbuzhixi.com,api.yongbuzhixi.com
          - LETSENCRYPT_HOST=api.staging.yongbuzhixi.com,api.yongbuzhixi.com
          - LETSENCRYPT_EMAIL=dale.tel@139.com
    drupal:
        image: drupal:fpm
        container_name: api_drupal
        restart: always
        network_mode: "bridge"
        links:
          - "db"
        volumes:
          - "./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro"
          - "./code/modules:/var/www/html/modules:ro"
          - "./code/themes:/var/www/html/themes:ro"
          - "./code/libraries:/var/www/html/libraries:ro"
          - "./code/sites/default/files:/var/www/html/sites/default/files:rw"
    db:
      image: mariadb:latest
      container_name: api_db
      restart: always
      network_mode: "bridge"
      volumes:
        - "./sql:/sql:ro"
        - "./sql/data:/var/lib/mysql"
      environment:
        - MYSQL_USER=drupal
        - MYSQL_PASSWORD=drupal
        - MYSQL_DATABASE=drupal
        - MYSQL_ROOT_PASSWORD=drupal